### PR TITLE
feat: Visual indicator for External link in the sidebar

### LINKED ISSUE #240: Visual indicator for External link in the sidebar

### PR DESCRIPTION
**Pull request by oodamien**
Resolves #240

For external link(s), add icon and target blank (open in a new tab)

### CODE REVIEW

**Comment by oodamien** [comment]
image

**Comment by rwinch** [comment]
@oodamien This looks great! I think it was @philwebb that was looking for this feature, so it is probably best to get his feedback before merging.

**Comment by philwebb** [comment]
It looks really nice, but I'm not sure how to go about setting `external: true` in our UI model. I'll need to investigate.

**Review by jonatan-ivanov — APPROVED** [review]

**Comment by philwebb** [comment]
I think we should also consider using an octicon like we do for the admonitionblock css. There's https://primer.style/foundations/icons/link-external-16 which we should be able to include if we update the `generate-octicons.js` script.

**Comment by philwebb** [comment]
I've done some work on an extension to allow us to attach attributes to the nav tree. https://github.com/spring-io/antora-extensions/pull/27.

It still needs an end-to-end test with the UI.

**Comment by philwebb** [comment]
We think we should hold off on merging this until we have clarity around https://github.com/spring-io/antora-extensions/pull/27#issuecomment-2108247870.

**Comment by philwebb** [comment]
#244 provides an updated version of this PR that uses the recent role support that @rwinch pushed and octicons rather than fontawsome.

**Comment by oodamien** [comment]
Close in favor of https://github.com/spring-io/antora-ui-spring/pull/244

**Pull request closed without merging**
